# ============================================================
# 📊 BJ EXPERT SCAN - CHARTINK
# ============================================================
# 👤 NSE STOCK ANALYZER BY SUJOY ROY
# ============================================================

import streamlit as st

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="BJ Expert Scan",
    page_icon="📊",
    layout="wide"
)

# ============================================================
# TITLE
# ============================================================

st.title("📊 BJ EXPERT SCAN - LONG")

st.markdown(
    """
    ### Chartink Technical Scanner

    The scanner below opens the **BJ EXPERT SCAN LONG - YOUTUBE**
    Chartink screener.
    """
)

# ============================================================
# CHARTINK URL
# ============================================================

chartink_url = (
    "https://chartink.com/screener/"
    "bj-expert-scan-long-youtube-2"
)

# ============================================================
# OPEN CHARTINK BUTTON
# ============================================================

st.link_button(
    "🔗 OPEN CHARTINK SCANNER",
    chartink_url,
    use_container_width=True
)

#st.markdown("---")


# ============================================================
# INFORMATION
# ============================================================

#st.markdown("---")

st.info(
    """
    ℹ️ **Chartink Scanner**

    This scanner is hosted by Chartink. The scan conditions
    and results are generated by Chartink and may change
    independently of this Streamlit application.
    """
)

# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.caption(
    "📊 NSE STOCK ANALYZER BY SUJOY ROY"
)
